### ISSUE TITLE
No Subtitles being shown And fullscreen not doing anything

### ISSUE THREAD

**Issue by RuneMasterGaming** [YePpHa/crunchyroll-html5#1]
as the title says No subtitles are being shown and clicking fullscreen does nothing.
used on firefox with tampermonkey

**Comment by YePpHa** [comment]
Yes, I'm aware that it doesn't work on Firefox. Currently, it only works on Chrome.

**Comment by YePpHa** [comment]
I took some time to look into why it didn't work on Firefox:
- I fixed the issues with fullscreen not working due to the vendor prefixes not being used for Firefox (`moz`).
- I also completely changed the crypto library because of a weird issue that caused it to not work on Firefox but wasn't a problem on Chrome.

You can find the update here:
https://github.com/YePpHa/crunchyroll-html5/releases/tag/v0.1.4-beta

**Comment by RuneMasterGaming** [comment]
thanks
