### ISSUE TITLE
Subs switched off for every video?

### ISSUE THREAD

**Issue by valdearg** [YePpHa/crunchyroll-html5#117]
I've just come to watch from CR videos for the first time in a while and just noticed that every time I load a video the subtitles are set to off. Even if I set them to English (US) and go to the next video it's off again.

Has anyone else come across this? I'm running version 0.13.1 which seems to be the latest version. 

I've tried it on a couple of series so far and it's the same.

Any logs that I can provide if it helps?

**Comment by YePpHa** [comment]
@valdearg have you tried going to https://www.crunchyroll.com/acct/?action=video to check whether `Default Language` is set to `English (US)`?

**Comment by valdearg** [comment]
My default language is set to English (UK), it used to fallover to the English (US) for both the default CR player and the HTML5 plugin.

**Comment by YePpHa** [comment]
Okay, I think I know what the reason is. In the new HTML5 player CR is pushing out they don't set what subtitle is default (this is what I used to determine what I showed by default). In the new HTML5 player they give the language and I do a simple comparison with the preferred language and the subtitle language instead. However, if your preferred language isn't found as a subtitle I don't have a fallback to i.e. English.

The temporary fix is that you can change your `Default Language` to `English (US)` and I will sometime this week make a fix which will set it to prefer English (US) subtitles if your preferred language isn't found.

**Comment by valdearg** [comment]
Sounds like an excellent idea. I shall change this next time I use it. 

Cheers for taking a look.

**Comment by YePpHa** [comment]
Should be fixed in the latest version I just released: https://github.com/YePpHa/crunchyroll-html5/releases/tag/v0.14.0
