### ISSUE TITLE
Subtitle language fallback to english if default language not exists.

### ISSUE THREAD

**Issue by DarkCloud14** [YePpHa/crunchyroll-html5#164]
Hi there,

I really like this extension and html5 player more than the original crunchyroll html5 as that one lacks several features..

One thing that you could enhance would be the choosen subtitle language if the default crunchyroll subtitle language doesn't exist.
I've German as my default subtitle language but if I watch episodes that don't have german subtitles the player will switch to some unknown subtitle language.
It would be great if it could switch to English (US) instead.

**Comment by jdale88** [comment]
This seems to be a new issue too, as my language is set to "English (UK)" and each time I've started a video in the past few days it has defaulted to some bogus subtitle language which I've had to change it to "English (US)" manually each time.

**Comment by valdearg** [comment]
Glad that this one isn't just me, I started getting the bogus subtitle language yesterday. 

I've set my default language to English (US) in the CR settings for the moment which resolves the issue for now.

**Comment by mikeloeven** [comment]
Gotten worse CR is not rendering any subtitles for me

**Comment by YePpHa** [comment]
I've found the issue and I'm going to release a fix for it real soon.

The issue is that they've probably removed the en-GB language. It tries to find your preferred language in the list of subtitles (this includes hard subs). If it's unable to find it it will select one of the unknown hardsubs. An unknown hardsub is a video stream that don't specify the language of the hardsub. In some shows (e.g. [Naruto](https://www.crunchyroll.com/naruto/episode-209-the-enemy-ninja-dropouts-535214)) they have specified the sub language for all languages except for en-US. So if it's unable to find your preferred subtitle language it will fallback to the first unknown hardsub due to the reason above.

The fix I've tried is to simply make a check before I fallback to the hardsub for whether en-US exists if no default subtitles match your preferred language and set en-US to the default if found.

Another note. I've noticed they've began having some kind of DRM streams too. I will try to filter them completely as they're the reason there's so many Unknown subtitles.

**Comment by YePpHa** [comment]
Just a quick update. I've uploaded the update to both the Chrome Web Store and Mozilla Add-on site. For Chrome there can go up to an hour before the update will be available (if nothing else happens).

**Comment by YePpHa** [comment]
It's pending a review on the Chrome web store. So it will probably take a couple of days before it's up. In the mean time you can side load the extension.

**Comment by DarkCloud14** [comment]
Awesome, works like a charm at least for those shows I watch!
Thanks for the quick fix!
