### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://accounts.google.com') does not match the recipient window's origin ('http://www.crunchyroll.com')

### ISSUE THREAD

**Issue by cAstraea** [YePpHa/crunchyroll-html5#17]
Been getting this lately ? Not sure where it's coming from though. 
Seems to be related to this  https://github.com/videojs/videojs-youtube/issues/67

**Comment by YePpHa** [comment]
Crunchyroll HTML5 player doesn't use videojs at all. Moreover, it doesn't use iframes that connects to `https://accounts.google.com`.

This issue is very likely caused by Crunchyroll itself as they don't use HTTPS (kind of stupid if you ask me) and they're probably using some kind of library that connects to Google (perhaps analytics).

I would recommend you to send them the issue instead as I will not be able to do anything about this.
