### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by Shinji1988** [YePpHa/crunchyroll-html5#20]
on newer episodes CR responds with different CORS headers.

`Access-Control-Allow-Origin: https://static.vrv.co`

for example in `Laid-Back Camp Episode 10`

the video gets blocked now because of not matching origin headers

**Comment by YePpHa** [comment]
Seems like the `Access-Control-Allow-Origin` has been fixed or something.

I might try to experiment with passing the requests when needed through the background or `GM.xmlHttpRequest`.

**Comment by Shinji1988** [comment]
`The 'Access-Control-Allow-Origin' header has a value 'https://static.vrv.co' that is not equal to the supplied origin. Origin 'http://www.crunchyroll.com' is therefore not allowed access.`

is what im getting on v0.5.3. 

I did try to figure it out by myself and got it working by passing a custom loader to the HLS player that does the whole thing with `GM_xmlhttpRequest`

**Comment by YePpHa** [comment]
I've been looking at this a bit more and there was a very easy fix for the web extension. However, for the userscript it was a bit more complicated.

I've copied their loader and modified it a bit to switch to using `GM_xmlhttpRequest` if it detects an error with status being 0 (XMLHttpRequest will always use status 0 for when it can't connect to a server due to 'Access-Control-Allow-Origin' header or something else).

There's an issue with the newest version of Greasemonkey 4.x it doesn't support `abort()` yet. However, it shouldn't prevent the video from loading.

Moreover, the biggest drawback from using `GM_xmlhttpRequest` is that it causes considerably more CPU usage due to it having to serialize the response (video + audio) to allow it to be transferred to the userscript. The video is still playable, but the UI will get a bit sluggish and there's nothing I can do about that except for recommend you to use the WebExtension.

I've made the [`experiment-hls-background`](https://github.com/YePpHa/crunchyroll-html5/tree/experiment-hls-background) branch with these changes.

You can download the build artifacts from the branch above:
[crunchyroll-html5.user.js.zip](https://github.com/YePpHa/crunchyroll-html5/files/1815652/crunchyroll-html5.user.js.zip)
[webextension.zip](https://github.com/YePpHa/crunchyroll-html5/files/1815653/webextension.zip)
