### ISSUE TITLE
Video plays is not working in Firefox

### ISSUE THREAD

**Issue by vickael** [YePpHa/crunchyroll-html5#45]
It loads infinitely and does not start.

Version: crunchyroll_html5-0.10.0-an.fx.xpi
Tested at: Ubuntu 18.04 and Fedora 28
Firefox Quantum 59.0.2

**Comment by YePpHa** [comment]
Does it work on the previous version? https://github.com/YePpHa/crunchyroll-html5/releases/tag/v0.9.4

**Comment by vickael** [comment]
Previous version only work on Ubuntu, in Fedora does not work.

**Comment by vickael** [comment]
This new version still does not work on Ubuntu 18.04.

**Comment by vickael** [comment]
Now it working, Firefox updated to version 60.0, so now work at Ubuntu 18.04.

**Comment by irgendwie** [comment]
I'm using vers. 10.0.2 of the Firefox extension in Firefox vers. 60.0.1 (on ArchLinux)

This error happens for a lot of series for me when they are not working at all (preview image, no loading icon, no nothing):

![2018-05-25-183133_1722x31_scrot](https://user-images.githubusercontent.com/8360698/40555584-e2408924-6049-11e8-8fed-403a47f51f0d.png)
```Error: Element file not found.  content-script.js:1:17590```

E.g. http://www.crunchyroll.com/to-be-heroine/episode-1-being-from-another-world-771461

---

As a side note, when the player works, the time tracking isn't, although the corresponding request seems to be ACK by Crunchyroll:

![2018-05-25-183451_1730x298_scrot](https://user-images.githubusercontent.com/8360698/40555829-a9d8778a-604a-11e8-8565-d319b688b855.png)
```json
{
  "result_code": 1,
  "message_list": [
    {
      "type": "success",
      "message_body": "Success",
      "message_body_html": "Success",
      "data": [
        
      ]
    }
  ],
  "suggested_redirect_url": null,
  "data": [
    
  ],
  "exception_class": null,
  "exception_error_code": null
}
```

E.g. http://www.crunchyroll.com/ms-koizumi-loves-ramen-noodles/episode-5-tomato-ramen-euglena-huge-line-758823

---

There are no problems at all when using the extension for chromium on chromium.
Or when using the userscript on firefox (with tampermonkey) - but then there is this huge subtitle delay and non-working ui.

---

I'd like to help debugging this issue but I'm not used to extension development in firefox. If you say what you need, I can provide logs and test stuff. Thanks for providing such an awesome extension / userscript!

**Comment by YePpHa** [comment]
@irgendwie it's very interesting that it says `Element file not found`. What that means is that from the xml file (the video details that I download from Crunchyroll) the `file` element (the element that tells me what video to play) is not present. This is required otherwise I can't play any video at all.

If you could go to http://www.crunchyroll.com/xml/?req=RpcApiVideoPlayer_GetStandardConfig&media_id=771461&video_format=108&video_quality=80&current_page=http%3A%2F%2Fwww.crunchyroll.com%2Fto-be-heroine%2Fepisode-1-being-from-another-world-771461 and send me the content of that page with the request headers (see image below and __remember to not send the cookies__).

![image](https://user-images.githubusercontent.com/2348303/40558314-337d19ac-6053-11e8-8c90-7beea08115c5.png)

**Comment by irgendwie** [comment]
Content of the xml response:

https://gist.github.com/irgendwie/0401ee63f8ac63affdd10f34cb7c9d08

and the request headers without the cookie:

![2018-05-25-200813_565x282_scrot](https://user-images.githubusercontent.com/8360698/40559560-73d55830-6057-11e8-9046-35490d663d61.png)

**Comment by YePpHa** [comment]
Yes, it makes sense that it's missing the file when there's no cookie (or using the default cookies) as it uses those to authenticate you (the episode is still for premium members only as of writing this).

So as for what I could decipher from what you wrote. The reason it had no cookies is because you used private mode. But what I don't get is that it should also not be logged in when you go to the video and instead show you that it's still premium only.

The most likely thing is that there's some kind of bug with XMLHttpRequest in content scripts on Firefox (or something I've misunderstood on Firefox) that makes it not use cookies in some special cases.

**Comment by irgendwie** [comment]
@YePpHa You are right, see my last and final edit :wink:

**Comment by YePpHa** [comment]
@irgendwie Nice find. I will definitely get this added in a PR soon. Probably tomorrow as I'm dead tired.

**Comment by YePpHa** [comment]
@irgendwie please test whether this PR works (#58) I've provided a webextension version (but not signed).
