### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mickymadfree** [YePpHa/crunchyroll-html5#5]
Add to Chrome (63.0.3239.132 64 bit) the directory "webextension". Check all subtitles, they are good. I watch with Russian subtitles, they are good. But the advertising do not work and HD available, I think it may bring some problems, probably block account. What do you think?
There will an option to add subtitles from file? What about to add an external audio or it is too difficult?

**Comment by YePpHa** [comment]
It would require them to detect it first and [adblock](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) is also able to remove ads from videoes. I have never heard about a user being blocked at all because of this. So I don't think you have to worry about that.

As for adding subtitles from a file is actually something I've been thinking about and I should make an issue about adding it.
As for the external audio file, I haven't really thought about it but that should be possible too, but a little bit more complicated (I'm using [hls.js](https://github.com/video-dev/hls.js)).

**Comment by Keiiko** [comment]
Hi, i would like also ask you if it would be possible to add custom subs

**Comment by YePpHa** [comment]
@Keiiko Check what I wrote in my comment above. Also #8.
