### ISSUE TITLE
Implement option to turn auto-play on or off

### ISSUE THREAD

**Issue by YePpHa** [YePpHa/crunchyroll-html5#72]

**Comment by TwistedAx** [comment]
Is there any chance this option to turn off automatic playback will get implemented sooner rather than later? And/Or perhaps and an option to slightly delay playing the next video?

Since the auto play next episode was introduced, the last 2 minuets of playback time for each episode's history is lost, until manually going back to replay the last 2 minuets.

P.S.: Love your work so far man, top tier stuff. Seriously.

**Comment by YePpHa** [comment]
@TwistedAx Please make a new feature request as I will close this as the option has been implemented.
